config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :markets, only: [:index, :show]
  resources :vendors, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/markets_controller.rb
class MarketsController < ApplicationController
  
  def index
    @facade = MarketsFacade.new.all_markets
  end

  def show
    market_id = params[:id]
    @facade = MarketsFacade.new.single_market(market_id)
    # to get vendors for the market
    @vendor_facade = MarketsFacade.new.market_vendors(market_id)
  end
  
end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController

  def show
    vendor_id = params[:id]
    @facade = VendorsFacade.new.single_vendor(vendor_id)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MarketMoneyFe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <style>
      /*Merchant Styles*/
      body {
      font-family: Arial, sans-serif;
      }
      .four-columns{
        display:flex;
      }

      .four-columns > * {
        width: 25%;
        padding: 1rem;
      }

      .market_sub {
        font-family: Arial;
        background-color: mediumseagreen;
        border-top: 2px solid #622583;
        padding: 2px 200px;
        text-align: center;
        float: left;
      }

      .button-container {
        white-space: nowrap; 
        /* Prevent line breaks */
      }

      .button-container form {
        display: inline-block; 
        /* Display the forms horizontally */
        margin-right: 4px; 
        /* Add some spacing between the buttons */
      }
    </style>
    <%= yield %>
  </body>
</html>

app/views/markets/index.html.erb
<body>
  <h3>Markets</h3>
  <div class="four-columns">
    <div class="market_sub">
      <b>Name</b>
      <% @facade.each do |market| %>
        <p><%= market.name %></p>
      <% end %>
    </div>

    <div class="market_sub">
      <b>City</b>
      <% @facade.each do |market| %>
        <p><%= market.city %></p>
      <% end %>
    </div>

    <div class="market_sub">
      <b>State</b>
      <% @facade.each do |market| %>
        <p><%= market.state %></p>
      <% end %>
    </div>

    <div class="market_sub">
      <b>More Info</b>
      <% @facade.each do |market| %>
      <div class="button-container">
        <p><%= button_to "More Info", market_path(market.id), method: :get %></p>
      <% end %>
    </div>
  </div>
</body>

app/views/markets/show.html.erb
<% @facade.each do |market| %>
  <h3><%= market.name%></h3>
  <%= market.street %><br>
  <%= [market.city, market.state, market.zip].compact.join(', ')%><br>
<%end%>
<h4>Vendors at our Market:</h4>
<% @vendor_facade.each do |vendor| %>
  <%= link_to vendor.name, vendor_path(vendor.id) %>
<%end%>

app/views/vendors/show.html.erb
<% @facade.each do |vendor| %>
<h1><%= vendor.name%></h1><br>
<h4>Contact Info:</h4>
<p>Name: <%= vendor.contact_name %></p>
<p>Phone: <%= vendor.contact_phone%></p><br>
<p>Credit Accepted?:<%= vendor.credit_accepted %></p><br>
<p>Description:<%= vendor.description %></p>
<%end%>